security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_GOV_AGENT:     ROLE_GOV_AGENT
        ROLE_CALL_OPERATOR: ROLE_CALL_OPERATOR
        ROLE_SUPER_ADMIN:   ROLE_SUPER_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/crisis/submit, role: [ROLE_CALL_OPERATOR, ROLE_SUPER_ADMIN] }
        - { path: ^/crisis/manage, role: [ROLE_CALL_OPERATOR, ROLE_GOV_AGENT, ROLE_SUPER_ADMIN] }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
