AppBundle\Entity\Assistance:
    type: entity
    table: assistance
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        wording:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        govAgencyName:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: gov_agency_name
        contactNumber:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: contact_number
    manyToMany:
        crisis:
            targetEntity: Crisis
            cascade: {  }
            fetch: LAZY
            mappedBy: assistance
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
