AppBundle\Entity\Request:
    type: entity
    table: request
    indexes:
        FK_request_crisis:
            columns:
                - crisis
        FK_request_category:
            columns:
                - assistance
    id:
        crisis:
            associationKey: true
        assistance:
            associationKey: true
    fields:
        sentAt:
            type: date
            nullable: false
            column: sent_at
        status:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    manyToOne:
        crisis:
            targetEntity: Crisis
            inversedBy: assistanceList
            joinColumn:
                name: crisis
                referencedColumnName: id
        assistance:
            targetEntity: Assistance
            inversedBy: crises
            joinColumn:
                name: assistance
                referencedColumnName: id
    lifecycleCallbacks: {  }
